### ISSUE TITLE
Error: no ports found after.... with budo server

### ISSUE THREAD

**Issue by whitecolor** [typicode/minihost#14]
Trying to start 
`h --n app -- babel-node server.js`

which runs [budo](https://github.com/mattdesl/budo) server.
it doesnt like so high ports:

```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: no ports found after 63062
    at app\node_modules\get-ports\index.js:24:28
    at app\node_modules\get-ports\index.js:37:9
```

Is it possible to run minihost on lower ports?

**Comment by typicode** [comment]
You can set a fixed port this way:

```
h --n app -p 4000 -- babel-node server.js
```

**Comment by whitecolor** [comment]
but if I don't want to set fixed port? what is a reasy to use so high ports (just to explain it to `budo` or `get-port`)

**Comment by typicode** [comment]
Sorry, I don't know the reason.
`get-port`and similar packages bind to port `0`  and the 0S randomly assigns a free port above `1024`.

However, I've never seen this particular error but would be interested if you find anything. You're on Windows?

**Comment by whitecolor** [comment]
Yes I'm on windows.

**Comment by typicode** [comment]
At first, I thought it was related to `get-port` which is used in `minihost`.
`get-ports`, the package used by `budo`, has a `DEFAULT_MAX_PORT` at `60000` and will throw an error if `port` is higher.

**Comment by whitecolor** [comment]
What to do?

**Comment by typicode** [comment]
I don't see a technical reason to limit to 60000, and it makes it complicated to work with modules that look for a free port using port 0. So I would suggest asking to raise the default max port to 65535.

**Comment by whitecolor** [comment]
Think can be closed.

**Comment by typicode** [comment]
You're welcome :)
