### ISSUE TITLE
Allow multiple names/ports mapping

### ISSUE THREAD

**Issue by whitecolor** [typicode/minihost#15]
What do you think about allowing multiple names/ports mapping? This may be needed if the process exposes multiple ports we want to map.

For example: using docker-compose to start multiple services, and may need to have access to multiple exposed ports (for example multiple web servers), currently using minihost it is possible to map only one exposed port, it would be nice to be able to do something like that:

``` js
"h --n my-app-web:WEB_PORT --n may-app-web2:ANOTHER_WEB_PORT -- docker-compose up"
```

So it would map two names to ports that will place in two ports that are in env vars WEB_PORT, ANOTHER_WEB_PORT.

**Comment by whitecolor** [comment]
@typicode I've added a PR (https://github.com/typicode/minihost/pull/16) it you ok with this change, I can add docs.

**Comment by typicode** [comment]
Hi @whitecolor,

It's a usage I've not thought about, it looks great :+1:
