### ISSUE TITLE
Can't start with custom script path

### ISSUE THREAD

**Issue by whitecolor** [typicode/minihost#2]
Can't implement this scenario:

`h --name my-name -- nodemon server/index.js`

```
Starting `nodemon server/index.js` on port 52610
Server is available at http://my-name.127.0.0.1.xip.io:2000

Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

I'm trying on widnows 7x64.

**Comment by typicode** [comment]
This means that the command is not found.
Could you try with `h -n  my-name -- nodemon.cmd server/index.js` please?

On Windows you may need to happen `.cmd`. I'll update the README if it works.

**Comment by typicode** [comment]
Just did a test on Windows 8, and that seems to be the reason.

**Comment by whitecolor** [comment]
Ok, I've added cmd and in console it seems to be started but when I go to `http://my-name.127.0.0.1.xip.io:2000` I see an error:
`
Error: connect ECONNREFUSED at errnoException (net.js:904:11) at Object.afterConnect [as oncomplete] (net.js:895:19)
`
There is also nothing on 52610 port.

**Comment by typicode** [comment]
How do you set the port in `index.js`?
Do you have something like:

```javascript
var port = process.env.PORT || 3000; // 3000 isn't really relevant here, the most important part is process.env.PORT
server.listen(port);
```

**Comment by whitecolor** [comment]
Yes this seems to work. I was redefining port. Thanks.)

**Comment by typicode** [comment]
Just as an update, you don't need to append `.cmd` anymore.
