### ISSUE TITLE
tries to find `node-dev` locally

### ISSUE THREAD

**Issue by whitecolor** [typicode/minihost#5]
In lastest version:
`h --n name -- node-dev server/index.js`

tries to find `node-dev` locally (in 0.3.8 it works, but requires `.cmd` in windows)

```
module.js:340
    throw err;
          ^
Error: Cannot find module '...\my-project\node_modules\node-dev\bin\node-dev'
```

The same behaviour with other global modules, though nodemon seemed to start.

**Comment by typicode** [comment]
Thanks for the issue. Just to let you know, I'm reproducing it
I've been usually testing with `nodemon` and `serve`, so there might be something different with `node-dev`.

I'll have a look, what are the other global modules it doesn't work with?

**Comment by whitecolor** [comment]
had problem with this
https://github.com/Alex0007/watchalive-runner/blob/master/index.js
it actully tries to start:
```javascript
cmd = 'h' + cmdPostfix + ' --n ' + options.minihost + ' -- '
```

**Comment by typicode** [comment]
Thanks for the issue, should be good in `v0.3.10`
