### ISSUE TITLE
localhost:2000 is not available in 0.3.11

### ISSUE THREAD

**Issue by whitecolor** [typicode/minihost#7]
At least on my dev win7 x64 localhost:2000 is not available in 0.3.11 

in 0.3.10 address is ok, but it works with bugs: 
1) I start first instance with name asy `app-first`
2) I start second instance with name asy `app-second`
3) try to got to http://app-second.127.0.0.1.xip.io:2000/ and it opens `app-first`
3) in locahost:2000 panel everything looks, so seems name/port mapping broken.

Have to use 0.3.5

**Comment by typicode** [comment]
Really sorry for that. Maybe it's related to Windows.
I've tried on Linux with v0.3.11, serve and node-static. 

```bash
# First tab
~/$ h -n app-first -- 'serve -p $PORT'

# Second tab
~/$ h -n app-second -- 'static -p $PORT'
```

And it works. I'll do some tests on Windows as soon as I can and add tests as well for that specific case.

**Comment by typicode** [comment]
Did some tests on Windows and just noticed that on Node 0.10 it doesn't work but on Node 0.12.
What's your version of Node?

**Comment by typicode** [comment]
Just added an `engines` property to `package.json` (not yet published) so that you get a warning if it's not the right version of Node. It will be more user-friendly this way.

**Comment by whitecolor** [comment]
Yes I'm using 0.10

**Comment by typicode** [comment]
Ok, that might be the cause. If you can update to 0.12, it should be good.

**Comment by whitecolor** [comment]
Thanks, will try ASAP)
